package test.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.id
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.login_name
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.user_name
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.password
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.gender
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.phone
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.email
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.address
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.status
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.create_date
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.update_date
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.SecretID
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private String secretid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_user.SecretKey
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    private String secretkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.id
     *
     * @return the value of ca_user.id
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.id
     *
     * @param id the value for ca_user.id
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.login_name
     *
     * @return the value of ca_user.login_name
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.login_name
     *
     * @param loginName the value for ca_user.login_name
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.user_name
     *
     * @return the value of ca_user.user_name
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.user_name
     *
     * @param userName the value for ca_user.user_name
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.password
     *
     * @return the value of ca_user.password
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.password
     *
     * @param password the value for ca_user.password
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.gender
     *
     * @return the value of ca_user.gender
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.gender
     *
     * @param gender the value for ca_user.gender
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.phone
     *
     * @return the value of ca_user.phone
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.phone
     *
     * @param phone the value for ca_user.phone
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.email
     *
     * @return the value of ca_user.email
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.email
     *
     * @param email the value for ca_user.email
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.address
     *
     * @return the value of ca_user.address
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.address
     *
     * @param address the value for ca_user.address
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.status
     *
     * @return the value of ca_user.status
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.status
     *
     * @param status the value for ca_user.status
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.create_date
     *
     * @return the value of ca_user.create_date
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.create_date
     *
     * @param createDate the value for ca_user.create_date
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.update_date
     *
     * @return the value of ca_user.update_date
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.update_date
     *
     * @param updateDate the value for ca_user.update_date
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.SecretID
     *
     * @return the value of ca_user.SecretID
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public String getSecretid() {
        return secretid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.SecretID
     *
     * @param secretid the value for ca_user.SecretID
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setSecretid(String secretid) {
        this.secretid = secretid == null ? null : secretid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_user.SecretKey
     *
     * @return the value of ca_user.SecretKey
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public String getSecretkey() {
        return secretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_user.SecretKey
     *
     * @param secretkey the value for ca_user.SecretKey
     *
     * @mbggenerated Mon May 16 11:40:15 CST 2016
     */
    public void setSecretkey(String secretkey) {
        this.secretkey = secretkey == null ? null : secretkey.trim();
    }
}